constants:
  
  
  obj: 'DIAMOND_ORE|DEEPSLATE_DIAMOND_ORE'
  td_obj1: Terminé
  t_reward: '&6+50 KGolds'
  
  qte1: '15'
  qte2: '30'
  qte3: '45'
  qte4: '60'

  money: '10'
  money2: '20'
  money3: '50'
  money4: '100'
  custom_reward: ''



