constants:
  
  obj: COD

  qte1: '10'
  qte2: '20'
  qte3: '30'
  qte4: '40'
  
  td_obj1: Terminé
  t_reward: '&6+50 KGolds'
  
  money: '10'
  money2: '20'
  money3: '50'
  money4: '100'
  custom_reward: ''



