constants:
  
  
  obj: 'GOLD_ORE|DEEPSLATE_GOLD_ORE'
  td_obj1: Terminé
  t_reward: '&6+50 KGolds'
  
  qte1: '32'
  qte2: '64'
  qte3: '87'
  qte4: '100'

  money: '10'
  money2: '20'
  money3: '50'
  money4: '100'
  custom_reward: ''



