constants:
  
  obj: SPIDER
  t_title: Tuer des araignées
  t_obj1: Tuer 5 Araignées
  td_obj1: Terminé
  t_reward: '&6+50 KGolds'
  
  money: '10'
  money2: '20'
  money3: '50'
  money4: '100'
  custom_reward: ''



