constants:
  
  
  obj: 'NETHER_QUARTZ_ORE'
  td_obj1: Terminé
  t_reward: '&6+50 KGolds'
  
  qte1: '128'
  qte2: '256'
  qte3: '512'
  qte4: '1024'

  money: '10'
  money2: '20'
  money3: '50'
  money4: '100'
  custom_reward: ''



